feat: add job to validate inputs variables

diff --git a/.github/workflows/commit_stage.yml b/.github/workflows/commit_stage.yml
--- a/.github/workflows/commit_stage.yml
+++ b/.github/workflows/commit_stage.yml
@@ -14,9 +14,69 @@ on :
       ALTERNATIVE_BASHUTILS_PATH:
         type: string
         default: "."
+permissions:
+  contents: write
+  actions: read
+  pull-requests: write
+  checks: write
+  packages: write
+  id-token: write
 
 jobs:
+  pre-workflow-checks:
+    runs-on: ubuntu-latest
+    env:
+      BUILD_DIR: ${{ vars.BUILD_DIR }}
+      MACOS_SIGNING_IDENTITY: ${{ vars.MACOS_SIGNING_IDENTITY }}
+      BUILD_WINDOWS: ${{ vars.BUILD_WINDOWS }}
+      BUILD_MACOS: ${{ vars.BUILD_MACOS }}
+      BUILD_LINUX: ${{ vars.BUILD_LINUX }}
+      RELEASE_MACOS: ${{ vars.RELEASE_MACOS }}
+      RELEASE_WINDOWS: ${{ vars.RELEASE_WINDOWS }}
+      RELEASE_LINUX: ${{ vars.RELEASE_LINUX }}
+      GTEST_FILTER: ${{ vars.GTEST_FILTER }}
+      LIB_NAME: ${{ vars.LIB_NAME }}
+      RUNNER_LABELS_MACOS: ${{ vars.RUNNER_LABELS_MACOS }}
+      RUNNER_LABELS_WINDOWS: ${{ vars.RUNNER_LABELS_WINDOWS }}
+      RUNNER_LABELS_LINUX: ${{ vars.RUNNER_LABELS_LINUX }}
+      APPLE_CERTIFICATES_P12_BASE64_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_P12_BASE64_PASSWORD }}
+      APPLE_CERTIFICATES_P12_BASE64: ${{ secrets.APPLE_CERTIFICATES_P12_BASE64 }}
+      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+
+    steps:
+      - uses: actions/checkout@v2
+      - name: Correct secrets and repository variables
+        run: |
+          required_vars=("BUILD_DIR" "MACOS_SIGNING_IDENTITY" "BUILD_WINDOWS" "BUILD_MACOS" "BUILD_LINUX" "RELEASE_MACOS" "RELEASE_WINDOWS" "RELEASE_LINUX" "GTEST_FILTER" "LIB_NAME" "RUNNER_LABELS_MACOS" "RUNNER_LABELS_WINDOWS" "RUNNER_LABELS_LINUX")
+          required_secrets=("APPLE_CERTIFICATES_P12_BASE64_PASSWORD" "APPLE_CERTIFICATES_P12_BASE64" "KEYCHAIN_PASSWORD")
+
+          printf "Checking required vars..."
+          continue=0
+          for var in "${required_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              continue=1
+              printf "\n❌ Variable '$var' is not set or is empty."
+            fi
+          done
+          if [ $continue = 0 ];then
+            printf "ok.\n"
+          fi
+
+          printf "\nChecking required secrets..."
+          for secret in "${required_secrets[@]}"; do
+            if [ -z "${!secret}" ]; then
+              continue=1
+              printf "\n❌ Secret '$secret' is not set or is empty."
+            fi
+          done
+          if [ $continue = 0 ];then
+            printf "ok.\n"
+          fi
+          exit $continue
+
+
   validate:
+    needs: pre-workflow-checks
     runs-on: windows-2022
     outputs:
       runners: ${{ steps.runners-matrix.outputs.runners }}
