feat: initial app workflow

diff --git a/.github/workflows/commit_stage.yml b/.github/workflows/commit_stage.yml
--- a/.github/workflows/commit_stage.yml
+++ b/.github/workflows/commit_stage.yml
@@ -10,6 +10,10 @@ on :
       PRIVATE_KEY_APP_CHECKOUT:
       PAT_CHECKOUT:
     inputs:
+      repository_type:
+        description: 'What is the type of repository. app or lib'
+        type: string
+        default: lib
       release:
         description: 'Should create a release and push C# bindings'
         type: string
@@ -35,6 +39,7 @@ jobs:
     outputs:
       matrix: ${{ steps.config-matrix.outputs.matrix }}
       LIB_NAME: ${{ steps.set-config.outputs.LIB_NAME }}
+      APP_NAME: ${{ steps.set-config.outputs.APP_NAME }}
       MACOS_SIGNING_IDENTITY: ${{ steps.set-config.outputs.MACOS_SIGNING_IDENTITY }}
       GTEST_FILTER: ${{ steps.set-config.outputs.GTEST_FILTER }}
       INCLUDE_NUGET_LA_FEED: ${{ steps.set-config.outputs.INCLUDE_NUGET_LA_FEED }}
@@ -48,6 +53,12 @@ jobs:
         id: set-config
         shell: bash
         run: |
+          repository_type=${{inputs.repository_type}}
+          if [[ $repository_type != 'lib' && $repository_type != 'app' ]];then
+            echo "ERROR: Repository type \"$repository_type\" is not supported. Please use \"lib\" or \"app\" "
+            exit 1
+          fi
+
           # # Required variables
           # Required so that the json string is parsed correctly
           build_config=${{vars.BUILD_CONFIG}}
@@ -67,6 +78,7 @@ jobs:
           lib_name=$(echo $build_config | jq -e -c '.package_name')
           macos_signing_identity=$(echo $build_config | jq -e -c '.macos_signing_identity')
           echo "LIB_NAME=$lib_name" >> $GITHUB_OUTPUT
+          echo "APP_NAME=$lib_name" >> $GITHUB_OUTPUT
           echo "MACOS_SIGNING_IDENTITY=$macos_signing_identity" >> $GITHUB_OUTPUT
 
           # # Optional variables using jq and echo-ing the fallback value if any errors during parsing.
@@ -237,6 +249,7 @@ jobs:
       with:
         submodules: recursive
     - uses: L-Acoustics/la-mw-gh-action/.github/actions/la-swig@v3
+      if: inputs.repository_type == 'lib'
       name: Install custom SWIG
       id: la_swig
       with:
@@ -244,7 +257,7 @@ jobs:
 
 
     - name: Configure runner
-      uses: L-Acoustics/la-mw-gh-action/.github/actions/la-configure-runner@v3
+      uses: L-Acoustics/la-mw-gh-action/.github/actions/la-configure-runner@dev
       with:
         WINPCAP_ROOT_DESTINATION: ${{needs.pre-workflow-checks.outputs.WINPCAP_ROOT_DESTINATION}}
         APPLE_CERTIFICATES_P12_BASE64_PASSWORD: ${{secrets.APPLE_CERTIFICATES_P12_BASE64_PASSWORD}}
@@ -252,8 +265,21 @@ jobs:
         KEYCHAIN_PASSWORD: ${{secrets.KEYCHAIN_PASSWORD}}
         setup_keychain: "true"
 
+    - name: Build and Test App
+      uses: L-Acoustics/la-mw-gh-action/.github/actions/la-build-app@dev
+      if: inputs.repository_type == 'app'
+      with:
+        RUNNER_ARCH: ${{matrix.arch}}
+        GTEST_FILTER: '${{needs.pre-workflow-checks.outputs.GTEST_FILTER}}'
+        BUILD_DIR: "${{needs.pre-workflow-checks.outputs.BUILD_DIR}}"
+        CONFIG: ${{matrix.config}}
+        MACOS_SIGNING_IDENTITY: ${{needs.pre-workflow-checks.outputs.MACOS_SIGNING_IDENTITY}}
+        APP_NAME: ${{needs.pre-workflow-checks.outputs.APP_NAME}}
+        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
+
     - name: Build and Test Library
       uses: L-Acoustics/la-mw-gh-action/.github/actions/la-build@v3
+      if: inputs.repository_type == 'lib'
       with:
         push_bindings: "${{ inputs.release == 'true' || github.ref_type == 'tag' }}"
         RUNNER_ARCH: ${{matrix.arch}}
